name: html5_dnd
version: 0.3.0
author: Marco Jakob <majakob@gmx.ch>
description: HTML5 Drag and Drop
homepage: https://github.com/marcojakob/dart-html5-dnd
documentation: http://edu.makery.ch/projects/dart-html5-drag-and-drop
dependencies:
  logging: '>=0.5.13 <0.5.14'
  meta: '>=0.5.13 <0.5.14'
dev_dependencies:
  browser: any
  logging_handlers: any
