name: html5_dnd
version: 0.3.6
author: Marco Jakob <majakob@gmx.ch>
description: HTML5 Drag and Drop (not maintained any more)
homepage: https://github.com/marcojakob/dart-html5-dnd
documentation: http://code.makery.ch/dart/html5-drag-and-drop/
dependencies:
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  browser: '>=0.9.0 <0.10.0'
  intl: '>=0.9.0 <0.10.0'
