name: html5_dnd
version: 0.3.3
author: Marco Jakob <majakob@gmx.ch>
description: HTML5 Drag and Drop
homepage: https://github.com/marcojakob/dart-html5-dnd
documentation: http://edu.makery.ch/projects/dart-html5-drag-and-drop
dependencies:
  logging: any
  meta: any
dev_dependencies:
  browser: any
  logging_handlers: any
